version: "3.0"
 
services:
  web:
    image: registration_form:1.0.1
    build: .
    command: gunicorn registration_form.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/registration_form
      - static:/staticfiles/
      - media:/mediafiles/
    expose:
      - 8000
    env_file:
    - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - 80:80
#      - 443:81
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    depends_on:
      - web

volumes:
  static:
  media: